# Generated by Django 5.2.8 on 2025-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_course_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='periods',
            field=models.JSONField(blank=True, default=list, help_text='List of period numbers (1-13) when this course meets'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
