# Generated by Django 5.2.8 on 2025-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_course_periods_alter_course_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='source_filename',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='chinese_level',
            field=models.IntegerField(default=0, help_text='Chinese proficiency level 0-6'),
        ),
    ]
