# Generated by Django 5.2.8 on 2025-11-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_country_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text="Term identifier (e.g., '2025-2026-1', '2024-2025-2')", max_length=64, unique=True)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=64)),
                ('semester', models.PositiveIntegerField(help_text='Semester number (1 or 2)')),
                ('first_week_monday', models.DateField(help_text='The official Monday date of week 1 for this term', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this term configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['-academic_year', '-semester'],
            },
        ),
    ]
