# Generated by Django 5.2.8 on 2025-11-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_academicterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='first_week_monday',
            field=models.DateField(help_text='The official Monday date of week 1 for this term'),
        ),
    ]
